# tally_shifts.py

import pandas


def tally_shifts(tidy_schedule: pandas.DataFrame) -> pandas.DataFrame:
    """
    Takes a tidy schedule generated by load_tidy_schedule() and generates a
    table of shift tallies per doctor.

    :param tidy_schedule: A data frame generated by load_tidy_schedule().
    :type tidy_schedule: pandas.DataFrame
    :return: A data frame with tallies of shift types per doctor.
    :rtype: pandas.DataFrame
    """
    return_table = (
        tidy_schedule
        .groupby(['doctor_name', 'shift_type'])
        .count()
        .reset_index()
        .pivot(index='doctor_name', columns='shift_type')
        .droplevel(0, axis=1)
    )

    return return_table
